### ISSUE TITLE
Better Bios

### ISSUE THREAD

**Issue by BrianL3** [CouncilDataProject/cdp-frontend#151]
### Biographies for People Could be Better

Biographies, as seen in the component <Biography> are implemented in an unfinished state. 

- They currently are not sensitive to the Person's current role.
- They are not localized.
- The sentence for number of terms served is not necessarily accurate.
- See line 40, filterRolesByTitle - We want to filter by ROLE_TITLE.COUNCILMEMBER here to get the number of roles for which the person is a council member in order to get how many terms the person has served. However, there aren't any roles in the DB with title == COUNCILMEMBER (this is probably a backend issue).
Or we can filter by role.body.name == "City Council" to get the correct number of roles to determine the number of terms.
But both methods of determining how many terms the person has served isn't accurate if the backend doesn't backfill data. For example, if the backend starts collecting data only recently the number of terms could be inaccurate.

I think what we want to do is break down all possible Roles and have custom helper sentence constructors for each.  The writeBiography function can then distinguish between roles that the Person has had in the past, is currently serving, etc, and be much more robust.

Perhaps the most important part of this feature is testing.

### Use Case

Once we have a more robust writeBiography in place, every Person no matter their current or past role will have a biography generated that makes sense.

### Solution

Done When:

- Fix the things listed under the top section.
- Storybook has bios for every role/person type including edge cases.

**Comment by tohuynh** [comment]
> However, there aren't any roles in the DB with title == COUNCILMEMBER (this is probably a backend issue).

I was wrong. There are COUNCILMEMBER roles in the DB. It was just that there was a bug in [`Role.ts`](https://github.com/CouncilDataProject/cdp-frontend/blob/main/src/models/Role.ts#L27). This code actually changes all role titles to `Member`. 

The bug is fixed in #160 https://github.com/tohuynh/cdp-frontend/blob/fix/seat-person-image/src/models/Role.ts#L27

**Comment by tohuynh** [comment]
@JacksonMaxfield Should we include "This is their nth term" to specify how many terms the council member has served?

If yes, how would we calculate this information? Count the number of `Councilmember` roles? This information could be inaccurate if the instance doesn't backfill the data. Maybe could write "this is their nth term since {datetime of when the instance as created}"?

**Comment by JacksonMaxfield** [comment]
Hmmmm. I would include that information but with an asterisk or something that the user can hover over for "since datetime of furthest back event"

**Comment by tohuynh** [comment]
Do we need a design task for this biography section? It's a little underspecified in the design recommendations: https://docs.google.com/presentation/d/15rkic20QV6GU0_nL-8zHIgcw8-o1bCQIiYMsY2j6qFg/edit#slide=id.g8c29f09c95_0_95
