### ISSUE TITLE
Paginate the person's voting records

### ISSUE THREAD

**Issue by tohuynh** [CouncilDataProject/cdp-frontend#156]
### Feature Description

Pagination the person's voting records

### Use Case

Currently, all of the person's voting records are initially retrieved. We can reduce the "time to interactivity" of the person page by first showing only N voting records and then allowing the user to show more voting records.

### Solution

Create some sort of `show more` UI to allow users to show more voting records.

### Alternatives

_Please describe any alternatives you've considered, even if you've dismissed them._

### Screenshots/References

_In the case of a visually oriented feature or component request, providing drawings, screenshots, and/or links to examples of what you're seeking will be very helpful._

**Comment by JacksonMaxfield** [comment]
Bump in priority: Seattle production instance now has so much data that trying to load the person voting record page fails because Firebase rejects requests when they come in that fast.

See: http://councildataproject.org/seattle/#/people/6410ce724625

And try to load the voting records.

![image](https://user-images.githubusercontent.com/17132317/155931217-b2ad016e-7cf0-4911-984e-073e55aa29c2.png)

Tested locally by adding a `limit(n)` to the options:
```typescript
const networkQueryResponse = this.networkService.getDocuments(
  COLLECTION_NAME.Vote,
  [
    where(
      REF_PROPERTY_NAME.VotePersonRef,
      WHERE_OPERATOR.eq,
      doc(NetworkService.getDb(), COLLECTION_NAME.Person, personId)
    ),
    limit(200),
  ],
  new PopulationOptions([populateMatter, populateEvent, populateEventMinutesItem])
);
```

And it works again so seemingly we just need to paginate this.

Longer term we definitely need to come up with a plan for filtering and sorting these rows but at least getting it to render / load would be the bugfix.

**Comment by JacksonMaxfield** [comment]
cc @BrianL3

**Comment by JacksonMaxfield** [comment]
Reminder: this is Seattle production ("cdp-seattle-21723dcf") not Seattle staging. Probably use prod when testing this locally.

I have been backfilling all of 2021 events for Seattle in which is what caused this. So honestly, its a "good problem to have" in my book :sweat_smile:

**Comment by tohuynh** [comment]
Will work on this
