### ISSUE TITLE
[f_legislationtracking] Legislation latest vote component

### ISSUE THREAD

**Issue by tohuynh** [CouncilDataProject/cdp-frontend#174]
Implement the Legislation latest vote component of the legislation details page (`/matters/:id`).

See the figma lofi mocks ups https://www.figma.com/file/VPeHF2SVDn6FneLLl9bihB/Legislation-Tracking-(CDP)?node-id=137%3A350

![image](https://user-images.githubusercontent.com/37560480/149586467-8108cb24-4a20-412b-9774-731059f51867.png)

- The vote (Yay, Nay, etc) should use our `VOTE_DECISION` constants
- The council member should link to the `/people/:id` page

**Comment by JacksonMaxfield** [comment]
Can I argue for using the horizontal split bar chart instead of the donut chart?

![image](https://user-images.githubusercontent.com/17132317/149588335-7a43a116-8012-4780-92a0-245db9913bb8.png)

But instead of it just being black bars make it colorful like the donut chart. Allows us to keep the same order for the bars and will always show an empty bar for 0 or something similar.

**Comment by tohuynh** [comment]
> Can I argue for using the horizontal split bar chart instead of the donut chart?

Yes
