### ISSUE TITLE
[Design Pass] Replacing Biographies

### ISSUE THREAD

**Issue by BrianL3** [CouncilDataProject/cdp-frontend#179]
### Feature Description

After some discussion, the biographies on an individual Person's page should probably _not_ be done via some formula-generated sentences.  It is difficult to localize, has some strange quirks when it comes to position names, and does not clearly show the Person's "career" of roles across time.

We need a solution that more cleanly displays a Person's Roles, while maintaining visibility of their current Seat. 

### Solution

@tohuynh has suggested the following:

At the top of the page, we have
```
Person name (inactive/active badge) (or add the start_datetime and/or end_datetime somewhere)
Seat name -- seat electoral area
seat picture and person picture

Previous term:
  <list of previous terms>

Committees (non-councilmember roles):
  <list of active roles>
  <list of inactive roles, initially hidden like accordion maybe?>

Matter Sponsored:
  <list of matters sponsored>
```
#### (minus things like past/inactive roles, timeline of role as council member)
![Proposed Look](https://user-images.githubusercontent.com/37560480/149647232-1c42655c-94e5-4097-b922-8ac4924208f0.png)

### Current Look
![Current Look](https://user-images.githubusercontent.com/9027758/150028611-2c265466-4647-4859-9400-eff7b1aa6a13.png)

**Comment by tohuynh** [comment]
Suggestions from Neha and Dale:

- The order of person name, seat information, pictures should be
```
seat picture and person picture
person name (inactive/active)
seat name -- seat electoral area
```
- add location icon left of "seat name -- electoral area"
- add icons left of "Previous terms", "Committees", and "Matter sponsored" to make the page more visual
- A summary of the person's voting records to quickly identify how many they vote for/against a specific legislation

I like all these ideas. Regarding a summary of the person's voting records, it would be not needed if we had filtering/searching on the person's voting records?

**Comment by tohuynh** [comment]
### to do
- `h2` Contact, Terms, Legislation Sponsored
- add `hr` between contact/terms and legislation sponsored, or add icons to the left of each title
- Increase font size
- add phone and email icon to left of phone and email
- “Committee Membership” and “Former Committee Membership” instead of "active" vs "inactive" committees
- Link each committee to search events page, with results filtered by committee id

### Next pr
- paginate legislations sponsored
- link to legislation pages, when it's ready
- still need think about whether to turn legislation sponsored into a table with more data. i think if users want to see the outcomes of legislation sponsored, they would just visit the legislation page. Adding more data here increases load time

@BrianL3 @JacksonMaxfield Sounds alright?

**Comment by JacksonMaxfield** [comment]
That all sounds good to me!

**Comment by tohuynh** [comment]
Closing in favor of #195 #194 #166 #156
