### ISSUE TITLE
Search transcript field should ignore case during search

### ISSUE THREAD

**Issue by evamaxfield** [CouncilDataProject/cdp-frontend#243]
https://www.openmontana.org/missoula-council-data-project/#/events/3ba34090b674

Reported by Mark from DemocracyLab.

If you type in "Abortion" in the "Search transcript" nothing is returned. If you type in "abortion" in the "Search transcript" it properly returns 9 results.

It looks like we are currently calling lowercase on the string but maybe we need to move that lowercasing to before the stemming? https://github.com/CouncilDataProject/cdp-frontend/blob/main/src/components/Details/TranscriptSearch/TranscriptSearch.tsx#L90

**Comment by jonlin14** [comment]
Yes it looks like the lowercasing needs to happen before the stemming.
<img width="529" alt="Screen Shot 2023-02-14 at 10 26 30 AM" src="https://user-images.githubusercontent.com/10490944/218836019-0f36bc79-f7b7-4294-a54b-26beddb1bf5c.png">
abortion gets stemmed to abort here

<br><br><br>

<img width="451" alt="Screen Shot 2023-02-14 at 10 25 00 AM" src="https://user-images.githubusercontent.com/10490944/218836251-a0a62961-88d1-47e2-a03f-907f7a5c491f.png">

but if we have a upperCase "Abortion", the stemr library does not stem it. Then we lowerCase "Abortion" into "abortion" and now we're searching with the term "abortion" which we won't find because the stemmedSentences only has "abort".

At first I thought this was pronoun protection. So that if somebody were to search "Billings" looking for information about the city in Montana, they wouldn't get results about billing, but "Billings" does get stemmed into "bill" so I think it's just some upperCase words are just blind spots? If we lowerCase them first, this should be resolved.
